sudo: required
services:
  - docker
before_install:
  - docker build -t subodh15/dockerreact:latest -f Dockerfile.dev .
script:
  - docker run subodh15/dockerreact:latest -e CI=true npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: ap-south-1
#   app: "dockerreact"
#   bucketname: ""
#   env: ""
#   bucket_path: ""
#   on: 
#     branch: master